### ISSUE TITLE
Allow multiple tags

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/push-to-registry#6]
Sometimes I may want to update multiple tags with one image. For example, I want to tag my image with the git SHA but also `latest`, or a release tag.

I should be able to do this with one action call.

**Comment by tetchel** [comment]
This got some attention, so I will try and write a clearer requirement:

- We don't want to change the `tag` input because it should still point to the existing, "parent" image, that we will alias to have extra tags. 
- We can add a new input called `tag_aliases` (name is up for debate) which is a space-separated list of extra tags that we want to tag the parent image with, and then we will push the parent image as well as all the aliases.

Then when the action executes:
- First, find the image we're going to push, and pull it into Podman if it's from Docker.
- Before doing the `podman push`, do a `podman tag` for each tag alias that was provided.
- Then `podman pus` all the tags.

**Comment by tetchel** [comment]
@kameshsampath, @breucode, @mpreu, @TriplEight who thumbs-upped this issue, let me know if above makes sense for your requirement.

**Comment by TriplEight** [comment]
Thanks for @ing!
Would be really great to have similar behaviour in https://github.com/marketplace/actions/buildah-build action. They are pretty much connected and would be really nice to use them the way https://github.com/marketplace/actions/build-and-push-docker-images does.
My recent use case was building an ugly [workaround](https://github.com/paritytech/substrate-api-sidecar/blob/master/.github/workflows/publish-release-container.yml#L16) which effectively builds and pushes the similar image twice, in parallel, just in order to have two tags.

> We don't want to change the tag input because it should still point to the existing, "parent" image, that we will alias to have extra tags.

What's the difference though? Anyway, this is the same image, just with two tags pointing at it. And doesn't really matter which of them is the "parent".

**Comment by tetchel** [comment]
> What's the difference though? Anyway, this is the same image, just with two tags pointing at it. And doesn't really matter which of them is the "parent".

My assumption was that the image would not be tagged more than once when the action started. Then, the action would do the tag duplication.

Maybe it makes more sense to allow `buildah-build` to output one image with multiple tags, and then have this action take _n_ tags which all must already exist?

**Comment by mpreu** [comment]
Thanks for the notification and the further discussion.

The workaround @TriplEight linked is a good example. I usually want/need to support multiple gliding tags along with unique tags for one image. Matrix build is a workaround, but in the end I need support for multiple tags as in the [docker/build-push-action](https://github.com/marketplace/actions/build-and-push-docker-images#inputs).

Due to the focus of this action to just push existing images, taking `n` input tags here makes sense to me if (`buildah-build` action can support multiple output tags).

**Comment by TriplEight** [comment]
It would be natural to build a `[list]` of tags and pass them to build and then to the push action.
But given that `podman` or `buildah` are able to take many `--tag` for `build` and (for some reason) just one tag for `push` command, it points to some inconsistency. But it's fine when you're in shell.
Github actions

**Comment by tetchel** [comment]
This is now available in the `v2` tags of `buildah-build` and `push-to-registry`.
